spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 300000
      connection-timeout: 30000

  apiKeys:
    weather: ${API_KEY_WEATHER}

  google:
    oauth:
      client-id: ${client-id}
      client-secret: ${client-secret}
      redirect-uri: ${redirect-uri}

  host:
    url-frontend-listener: ${HOST_URL_FRONTEND_LISTENER}

  JWT:
    secret: ${KEY_JWT_SECRET}
