spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: sa
    password: password

  apiKeys:
    weather: ${API_KEY_WEATHER}

  google:
    oauth:
      client-id: ${client-id}
      client-secret: ${client-secret}
      redirect-uri: ${redirect-uri}
